[build-system]
requires = ["setuptools", "setuptools_scm", "tox", "build", "twine"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/magic_module_scaffolder/_version.py"


